name: Deploy master stack
on:
  release:
    types:
      - created

jobs:
  provision-master-stack:
    name: Provision master stack
    runs-on: ubuntu-latest
    env:
      BRANCH: master
    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_CLOSESTWINS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_CLOSESTWINS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_CLOSESTWINS_REGION }}
      - uses: grishasergii/aws-cloudformation-provision-gh-action@v0.2.1
        with:
          stack_name: closestwins-storage
          branch: master
          path: ./templates/
          main_template: closestwins-storage.cfn
          artifacts_bucket: ${{ secrets.AWS_CLOSESTWINS_ARTIFACTS_BUCKET }}
          cfn_bucket: ${{ secrets.AWS_CLOSESTWINS_CFN_BUCKET }}
          cfn_aws_region: ${{ secrets.AWS_CLOSESTWINS_REGION }}
