name: Deploy master stack
on:
  push:
    branches:
      - master

jobs:
  provision-master-stack:
    name: Provision master stack
    uses: ./.github/workflows/deploy.yml
    with:
      branch: master
      environment: testing
    secrets:
      aws_access_key_id: ${{ secrets.AWS_CLOSESTWINS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_CLOSESTWINS_SECRET_ACCESS_KEY }}
      aws_region: ${{ secrets.AWS_CLOSESTWINS_REGION }}
      aws_artifacts_bucket: ${{ secrets.AWS_CLOSESTWINS_ARTIFACTS_BUCKET }}
      aws_cfn_bucket: ${{ secrets.AWS_CLOSESTWINS_CFN_BUCKET }}
