name: Deploy
on:
  workflow_call:
    inputs:
      branch:
        description: "A branch passed from the caller workflow"
        required: true
        type: string
      environment:
        description: "An environment passed from the caller workflow"
        required: true
        type: string
    secrets:
      aws_access_key_id:
        required: true
      aws_secret_access_key:
        required: true
      aws_region:
        required: true
      aws_artifacts_bucket:
        required: true
      aws_cfn_bucket:
        required: true

jobs:
  provision-master-stack:
    name: Provision stack
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws_access_key_id }}
          aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
          aws-region: ${{ secrets.aws_region }}
      - uses: ./actions/deploy
        with:
          branch: ${{ inputs.branch }}
          environment: ${{ inputs.environment }}
          aws_artifacts_bucket: ${{ secrets.aws_artifacts_bucket }}
          aws_cfn_bucket: ${{ secrets.aws_cfn_bucket }}
          aws_region: ${{ secrets.aws_region }}
